### ISSUE TITLE
Critical Fumbles

### ISSUE THREAD

**Issue by freiheit** [freiheit/MvKDiceBot#103]
> ## Critical Fumble
> A Critical Fumble means something has gone seriously wrong with your action/counter and within the scene. When you roll a 1 on a d20 die result it is considered a critical fumble. When this happens, you choose one other die in your pool that didn’t roll a 1 and scratch (remove) it. Calculate your action total and impact with your remaining die results. You may roll a critical fumble and still succeed in your action. 
>
> You also critically fumble if your action is successfully countered and you roll a 1-3 on the d20 (in other words if you fail to generate any impact at all).
>
> Whenever you roll a critical fumble, you gain 1 inspiration point. There’s nothing better than failure to spur you to success. 
>
> The GM will boost the lowest die in the Danger Dice and narrate how your fumble made the situation worse.

**Comment by freiheit** [comment]
@MechaVskaiju I think the only dice rolling rule the bot doesn't cover is fumbles.

I don't want to complicate things with any logic comparing rolls (counters), but should be easy enough to:
- If fortune die result is 1:
  - Remove (scratch) the lowest die that wasn't a 1 before any further calculations
  - Add some text about the fumble to the output

One clarification: if rolling with advantage, and 1 d20 rolls a 1, is that fumble? I'm assuming that with advantage, only the retained d20 is considered for any other rules.

Would look something like:
```
?r 1d20 4d8

Dice: 1d20[1] 4d8[4, 8, 3, 1]
Critical Fumble! Scratching 3 from dice.
New Dice: 1d20[1] 3d8[4, 8, 3]
Action Total: 12 [4, 8]
Impact: 2 (fortune=0 2x=0 1x=2)
```

**Comment by MechaVskaiju** [comment]
If you have advantage you keep the highest roll. The lower one doesn't
count at all.
