### ISSUE TITLE
d10+d12 gives 2 impact

### ISSUE THREAD

**Issue by MechaVskaiju** [freiheit/MvKDiceBot#27]
there's a rule I added recently that die results of 10 or higher on a d10 or 12 give two impact. It doesn't happen on a d20. Is there a way to add that?
If it helps dice d4-d12 are called "Character Dice" and the d20 is called the "Fortune Die". I don't know if you could impliment a rule that a 10+ result on Character Dice gives 2 impact
I know labeling things is critical in coding

**Comment by freiheit** [comment]
Ok, I think I've got this working right in dev...

![image](https://github.com/freiheit/MvKDiceBot/assets/19813/fdb24e7e-4cc6-4c2d-9191-b7500c9a002a)
