### ISSUE TITLE
Bug: Impact with advantage/disadvantage

### ISSUE THREAD

**Issue by freiheit** [freiheit/MvKDiceBot#31]
```
?r 2d20 10d12 10d10 advantage

Original d20s: 2d20[12, 19] 
Applying advantage...

Dice: 1d20[19] 10d12[5, 11, 2, 9, 12, 5, 3, 3, 11, 9] 10d10[1, 2, 3, 5, 1, 6, 8, 5, 5, 5] 
Action Total: 31 [19, 12]
Impact: 18 (fortune=2 2x=6 1x=10)
```

However, since the other d20 is discarded, should only use *1* d20 calculating impact...

**Comment by PedramHaeri** [comment]
Hi I would like to try and fix this issue. could you please assign it to me?

**Comment by freiheit** [comment]
@PedramHaeri Sure.

Should be fairly straightforward... When calculating the "fortune dice" impact, only look at the value of the retained dice not all the d20s; or just throw away all the other d20s after calculating which d20 is retained.

**Comment by freiheit** [comment]
Looks like PR #32 fixes this bug. I want to test a bit before considering this closed.
