### ISSUE TITLE
Remove need for a d20

### ISSUE THREAD

**Issue by MechaVskaiju** [freiheit/MvKDiceBot#54]
It's a handy feature to make sure people don't forget, however it makes it more difficult to roll individual dice.

**Comment by freiheit** [comment]
@MechaVskaiju I was thinking about this and wondering...
What if instead it _always_ included 1d20 in `?roll` (2d20 with advantage or disadvantage), and there was a separate command for a simple roll (doesn't add total, impact, etc)?

**Comment by MechaVskaiju** [comment]
Seems more complicated, adding an entirely extra kind of roll.

**Comment by freiheit** [comment]
> Seems more complicated, adding an entirely extra kind of roll.

It's really not too complicated, especially with the code cleanup that @slashingweapon did for us in #76 

It shows up as a second command (`?plainroll`), but in the code that uses the same `parse_dice()`, `roll_dice()` and `print_dice()` functions as `?roll` does, it just doesn't do all the extra math at all.

**Comment by freiheit** [comment]
Looks like this now:

```
?plainroll 1d20
Dice: 1d20[9]

?p 3d20 2d12 1d10
Dice: 3d20[6, 6, 1] 2d12[2, 4] 1d10[9]
```

And with the logic that mvk rolls have exactly 1d20, except with advantage or disadvantage (when it's _at least_ 2d20):
```
?r 1d12 1d10 2d8 3d6
No advantage/disadvantage, setting 1d20
Dice: 1d20[7] 1d12[5] 1d10[7] 2d8[2, 2] 3d6[3, 5, 3] 
Action Total: 14 [7, 7]
Impact: 4 (fortune=1 2x=0 1x=3)

?r 2d20 1d12 1d10 2d8 3d6
No advantage/disadvantage, setting 1d20
Dice: 1d20[10] 1d12[1] 1d10[1] 2d8[7, 8] 3d6[2, 3, 4] 
Action Total: 18 [10, 8]
Impact: 4 (fortune=1 2x=0 1x=3)

?r 1d12 1d10 2d8 3d6 advantage
Setting 2d20 for advantage/disadvantage
Original d20s: 2d20[8, 6] -- Applying advantage...
Dice: 1d20[8] 1d12[1] 1d10[6] 2d8[4, 6] 3d6[5, 5, 1] 
Action Total: 14 [8, 6]
Impact: 6 (fortune=1 2x=0 1x=5)

?r 1d20 1d12 1d10 2d8 3d6 advantage
Setting 2d20 for advantage/disadvantage
Original d20s: 2d20[20, 18] -- Applying advantage...
Dice: 1d20[20] 1d12[10] 1d10[1] 2d8[4, 5] 3d6[4, 5, 2] 
Action Total: 30 [20, 10]
Impact: 7 (fortune=1 2x=2 1x=4)

?r 2d20 1d12 1d10 2d8 3d6 advantage
Original d20s: 2d20[16, 14] -- Applying advantage...
Dice: 1d20[16] 1d12[11] 1d10[1] 2d8[4, 1] 3d6[1, 2, 1] 
Action Total: 27 [16, 11]
Impact: 4 (fortune=1 2x=2 1x=1)

?r 3d20 1d12 1d10 2d8 3d6 advantage
Original d20s: 3d20[11, 11, 4] -- Applying advantage...
Dice: 1d20[11] 1d12[8] 1d10[2] 2d8[4, 1] 3d6[4, 1, 4] 
Action Total: 19 [11, 8]
Impact: 5 (fortune=1 2x=0 1x=4)
```
